### ISSUE TITLE
Delay in history

### ISSUE THREAD

**Issue by BabyOilJohnson** [sadellie/unitto#75] opened 2023-07-23 14:35 UTC
There is a delay while swiping up/closing the history page.

**Comment by BabyOilJohnson** [comment] 2023-09-04 08:29
Thanks for the fix. But there is a small problem, when swiping up the history page doesn't completely close leaves a short portion there.
![Screenshot_20230904-135613_Calculator](https://github.com/sadellie/unitto/assets/101601874/15972e75-43d2-4fe3-a2a8-1bfe043d2acc)

**Comment by sadellie** [comment] 2023-09-04 08:43
Can you swipe up more to completely close it?

**Comment by BabyOilJohnson** [comment] 2023-09-04 08:45
I tried but I had to hold and drag up to close, can't close it by a single swipe.

**Comment by sadellie** [comment] 2023-09-04 09:19
It's a sort of intended behavior. You should be able to close by single swipe if you drag more. I will try to adjust the gesture so that it's easier to swipe

**Closed** 2023-09-30 20:31 UTC
Labels: bug, calculator
